### ISSUE TITLE
Missing package on v2.7.0

### ISSUE THREAD

**Issue by holymonson** [conda-forge/scrapy-feedstock#76]
Packages mentioned in #75 seems could not be ignored, otherwise it will fail with missing module

> ### Packages found by source code inspection but not in the meta.yaml:
> * h2
> * hpack
> * packaging
> 
> ### Packages found in the meta.yaml but not found by source code inspection:
> * pywin32
> 

```
❯ scrapy crawl  statement
Traceback (most recent call last):
  File "/usr/local/conda/envs/mas/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/conda/envs/mas/lib/python3.10/site-packages/scrapy/cmdline.py", line 133, in execute
    cmds = _get_commands_dict(settings, inproject)
  File "/usr/local/conda/envs/mas/lib/python3.10/site-packages/scrapy/cmdline.py", line 61, in _get_commands_dict
    cmds = _get_commands_from_module('scrapy.commands', inproject)
  File "/usr/local/conda/envs/mas/lib/python3.10/site-packages/scrapy/cmdline.py", line 42, in _get_commands_from_module
    for cmd in _iter_command_classes(module):
  File "/usr/local/conda/envs/mas/lib/python3.10/site-packages/scrapy/cmdline.py", line 29, in _iter_command_classes
    for module in walk_modules(module_name):
  File "/usr/local/conda/envs/mas/lib/python3.10/site-packages/scrapy/utils/misc.py", line 88, in walk_modules
    submod = import_module(fullpath)
  File "/usr/local/conda/envs/mas/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/conda/envs/mas/lib/python3.10/site-packages/scrapy/commands/parse.py", line 12, in <module>
    from scrapy.utils import display
  File "/usr/local/conda/envs/mas/lib/python3.10/site-packages/scrapy/utils/display.py", line 8, in <module>
    from packaging.version import Version as parse_version
ModuleNotFoundError: No module named 'packaging'

```

**Comment by Gallaecio** [comment]
Right, we added `packaging` as a dependency.
